### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by somehowchris**
This PR includes the following changes:
 - Github action building the project on push
 - Dependabot configuration (might be needed to be activated again on your repository)
 - Removing tokio as a dependency and using rockets tokio export
 - Upadting to rocket 0.5.0-rc.1
 - Updating the example in the readme
 - Adding a "Open in Gitpod" button alongside a basic `.gitpod.yml` file

Should I squash the commits or do you wanna leave them as is?

### CODE REVIEW

**Review by Ameobea — APPROVED** [review]
Thanks again!

**Comment by Ameobea** [comment]
Oh btw if you want to add yourself to the readme as a contributor feel free to do so

**Comment by somehowchris** [comment]
Like a list or some fany imagary?

## Contirbutors
- Casey Primozic ([Ameobea](https://github.com/Ameobea))
- Christof Weickhardt ([somehowchris](https://github.com/somehowchris))
---------------------------------------
## Contributors
<a href = "https://github.com/Tanu-N-Prabhu/Python/graphs/contributors">
  
</a>

**Comment by Ameobea** [comment]
Just a list I think, but if you want to have images that's ok with me.

**Comment by Ameobea** [comment]
I'll publish this to crates.io soon, about to take off on a plane atm

**Pull request merged**
